### ISSUE TITLE
Change image from intro container

### ISSUE THREAD

**Issue by jbastosufsc** [impuls-e/site#4]
Select a rocket or impulse image to exchange

**Comment by jbastosufsc** [comment]
![img01](https://user-images.githubusercontent.com/6197055/76124920-7e053080-5fda-11ea-908f-b900c44bef5a.jpg)
![img02](https://user-images.githubusercontent.com/6197055/76124923-7f365d80-5fda-11ea-8946-59720d2046d3.jpg)
![img03](https://user-images.githubusercontent.com/6197055/76124924-7fcef400-5fda-11ea-9049-067b756f35c0.jpg)
![img04](https://user-images.githubusercontent.com/6197055/76124929-80678a80-5fda-11ea-9156-184c2c0c0b0a.jpg)
![img05](https://user-images.githubusercontent.com/6197055/76124930-80678a80-5fda-11ea-8e5f-c75402c888f9.jpg)
![img06](https://user-images.githubusercontent.com/6197055/76124932-81002100-5fda-11ea-93af-bc2fe2eff45b.jpg)
![img07](https://user-images.githubusercontent.com/6197055/76124935-8198b780-5fda-11ea-9b7f-22a6fa0b0880.jpg)
![img08](https://user-images.githubusercontent.com/6197055/76124937-8198b780-5fda-11ea-93e4-c7d65f86ad84.jpg)
![img09](https://user-images.githubusercontent.com/6197055/76124939-82314e00-5fda-11ea-90af-22de536e8f90.jpg)

**Comment by ViniciusmDias** [comment]
Done
